baseurl = "https://usage.netlify.app/"
title = "日本語と韓国語の語法検索"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Seo Mincheol"
    avatar = "avatar.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        <i class='fas'>&#xf518;</i>を押すと，日本語と韓国語における（一部の）語法を，どのような本で取り上げているのか検索できます。<i class='fas'>&#xf002;</i>を押すと，言語学専門用語の検索ができます。<i class='fas fa-chalkboard-teacher'></i>では，利用方法や参考文献リストが確認できます。
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Search" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/usage/"
    weight = 10


[[menu.main]]
    identifier = "search"
    # name = "Glossary of Linguistic Terms"
    pre = "<i class='fas fa-search fa-lg'></i>"
    url = "https://terms.netlify.app/"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fas fa-chalkboard-teacher fa-lg'></i>"
    url = "https://www.notion.so/ffbceb3168d24c0fbd73dc592984a46d"
    weight = 30
